import puppeteer from 'puppeteer-core';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const mobile=process.argv.includes('--mobile'),reduced=process.argv.includes('--reduced'),label=process.argv[2]||'first';const width=mobile?390:1440,height=mobile?844:900;
const out=`docs/captures/hero-gallery-${label}${mobile?'-mobile':''}`;await fs.mkdir(out,{recursive:true});const wait=ms=>new Promise(r=>setTimeout(r,ms));
const b=await puppeteer.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
try{const p=await b.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.setViewport({width,height,isMobile:mobile,hasTouch:mobile});if(reduced)await p.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'reduce'}]);await p.goto('http://127.0.0.1:3333',{waitUntil:'networkidle2'});await p.waitForSelector('.gallery-loader',{hidden:true});await p.click('.garden-gate__enter');await p.waitForSelector('.entrance-gate',{hidden:true});await p.waitForSelector('.hero-surface[data-ready="true"]',{timeout:30000});await wait(1000);await p.screenshot({path:out+'/arrival.png'});
const rec=process.argv.includes('--record')?await p.screencast({path:out+'/interaction.mp4',format:'mp4',fps:30}):null;
async function point(x,y){if(mobile){const c=await p.createCDPSession();await c.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});await wait(400);await c.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await c.detach();}else await p.mouse.move(x,y,{steps:12});await wait(450);}
await point(width*.76,height*.61);await p.screenshot({path:out+'/relief-cats.png'});await point(width*.2,height*.73);await p.screenshot({path:out+'/relief-flower.png'});await point(width*.6,height*.18);await p.screenshot({path:out+'/relief-trail.png'});
if(!mobile){await p.mouse.move(width+50,height+50);await wait(2600);await p.screenshot({path:out+'/settled.png'});}
await p.click('.hero-gallery__theme');await wait(90);await p.screenshot({path:out+'/night-reveal-020.png'});await wait(140);await p.screenshot({path:out+'/night-reveal-050.png'});await wait(900);assert.equal(await p.$eval('.hero-gallery',e=>e.dataset.night),'true');await point(width*.28,height*.58);await p.screenshot({path:out+'/night-left.png'});await point(width*.78,height*.36);await p.screenshot({path:out+'/night-right.png'});
await p.click('.hero-gallery__photograph');await p.waitForSelector('.hero-portrait[open]');await wait(650);assert.equal(await p.$eval('.hero-surface__canvas',e=>e.dataset.renderState),'paused');assert.equal(await p.evaluate(()=>document.body.style.overflow),'hidden');await p.screenshot({path:out+'/photograph.png'});await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.querySelector('.hero-portrait'));assert.equal(await p.evaluate(()=>document.activeElement.className),'hero-gallery__photograph');
await p.click('.hero-gallery__theme');await wait(1500);assert.equal(await p.$eval('.hero-gallery',e=>e.dataset.night),'false');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await p.evaluate(()=>document.querySelector('.hero-gallery').getBoundingClientRect().height),height);
async function input(delta){if(!mobile)return p.mouse.wheel({deltaY:delta});const c=await p.createCDPSession(),sy=delta>0?650:170;await c.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:190,y:sy}]});await c.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:190,y:sy-delta}]});await c.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await c.detach();}
for(const direction of ['forward','reverse']){await p.screenshot({path:out+`/${direction}-000.png`});let previous=0;for(const percent of reduced?[100]:[20,40,50,60,80,100]){await input((percent-previous)/100*height*(direction==='forward'?1:-1));await wait(350);if(percent<100)await p.waitForFunction(expected=>Math.abs(+document.querySelector('#chapter-hero').dataset.handoffProgress-expected)<.003,{},(direction==='forward'?percent:100-percent)/100);else await p.waitForFunction(()=>!document.documentElement.dataset.heroGardenHandoff);await p.screenshot({path:out+`/${direction}-${String(percent).padStart(3,'0')}.png`});previous=percent;}if(direction==='forward'){await p.evaluate(()=>document.querySelector('#chapter-flowers').scrollIntoView({behavior:'instant'}));await wait(150);const before=await p.$eval('.garden-video',e=>e.currentTime);await wait(500);assert(await p.$eval('.garden-video',(e,before)=>!e.paused&&Math.abs(e.currentTime-before)>.03,before),'Garden autoplay advances, including loop wrap');}}
await p.click('.cinematic-hero__cta');await p.waitForFunction(()=>['active','completing'].includes(document.querySelector('#chapter-flowers').dataset.chapterState));assert.equal(await p.$eval('.hero-surface__canvas',e=>e.dataset.renderState),'paused');if(rec)await rec.stop();assert.deepEqual(errors,[]);console.log(out+': PASS GPU relief, night toggle, portrait focus/lock, swipe/wheel handoff both directions, CTA, autoplay, no errors');}finally{await b.close();}

